### ISSUE TITLE
Pre-Requisite: VirtualBox

### ISSUE THREAD

**Issue by infamousjoeg** [conjurdemos/kubernetes#1]
I reviewed the source code and didn't see why VirtualBox would be required.  Is this really a requirement of this scalability-demo?  Or would we be okay running this on a Conjur instance in a Docker host locally outside of VirtualBox?

**Comment by kgilpin** [comment]
Yes, I think it's not required. I am using minikube on Mac.

**Comment by jodyhuntatx** [comment]
I though minikube required vbox?? I'm using it that way on my mac. I'll try it w/o it.  Maybe that'll avoid the time sync issue?

**Comment by infamousjoeg** [comment]
Windows 10+ only requires Hyper-V
